name: "direnv-nix"
description: "Use a nix based direnv environment"
inputs:
    nix-cache-prefix:
        description: "Prefix for nix store cache key"
        required: false
        default: "nix-store"
    install-nix:
        description: "Include nix installation; disable if you installed it before"
        required: false
        default: "true"
    cache-store:
        description: "Cache nix store"
        required: false
        default: "true"
    export-all-vars:
        description: "Export all ENV vars direnv would touch, not just the PATH"
        required: false
        default: "true"
    nix_install_url:
        description: "Installation URL that will contain a script to install Nix."
        required: false
        default: "https://nixos.org/nix/install"
    nix_path:
        description: "If installing nix, Set NIX_PATH environment variable."
        required: false
        default: "nixpkgs=channel:nixos-unstable"
    extra_nix_config:
        description: "If installing nix, Set NIX_PATH environment variable."
        required: false
        default: |
            sandbox = false
runs:
    using: "composite"
    steps:
        # cache nix store https://github.com/cachix/install-nix-action/issues/56#issuecomment-1240991760
        - name: "Cache Nix store"
          uses: actions/cache@v3.0.11
          if: ${{ inputs.cache-store == 'true' }}
          id: nix-cache
          with:
              path: /tmp/nixcache
              key: ${{ format('{0}-{1}-{2}', runner.os, inputs.nix-cache-prefix, hashFiles('**/*.nix', '**/flake.lock')) }}
              restore-keys: |
                  ${{ format('{0}-{1}', runner.os, inputs.nix-cache-prefix) }}

        - uses: cachix/install-nix-action@v20
          if: ${{ inputs.install-nix == 'true' }}
          with:
              nix_path: ${{ inputs.nix_path }}
              install_url: ${{ inputs.nix_install_url }}
              extra_nix_config: ${{ inputs.extra_nix_config }}

        - name: "Import Nix store cache"
          shell: bash
          if: ${{ inputs.cache-store == 'true' && steps.nix-cache.outputs.cache-hit == 'true' }}
          run: |
              echo "::group::Nix store import"
              nix-store --import < /tmp/nixcache
              echo "::endgroup::"

        - name: "Setup Nix Environment"
          shell: bash
          run: |
              echo "::group::Nix Environment setup"
              nix-env --install --attr direnv nix-direnv -f '<nixpkgs>'
              echo "source $HOME/.nix-profile/share/nix-direnv/direnvrc" >> $HOME/.direnvrc
              direnv allow . 
              direnv exec / direnv export json > /tmp/direnv.out 
              echo "::endgroup::"

        - name: "Export Env vars and Path"
          uses: actions/github-script@v6
          with:
              script: |
                  const fs = require('fs')
                  const direnvExport = JSON.parse(fs.readFileSync('/tmp/direnv.out'))
                  console.log(core.getInput('export-all-vars', { required: false }))
                  const shouldExportEnvVars = (core.getInput('export-all-vars', { required: false }) || 'true') === 'true';
                  core.startGroup('DirEnvOutput')
                  core.info(JSON.stringify(direnvExport))
                  core.info(JSON.stringify(shouldExportEnvVars))
                  core.endGroup()

                  core.startGroup('export  debug')
                  Object.keys(direnvExport).forEach(function (name) {
                    const value = direnvExport[name];
                    if (name === 'PATH') {
                        core.addPath(value);
                    } else if (shouldExportEnvVars) {
                        core.info({name, value})
                        core.exportVariable(name, value);
                    }
                  });

                  core.endGroup()

        - name: "Export Nix store cache"
          shell: bash
          if: ${{ inputs.cache-store == 'true' && steps.nix-cache.outputs.cache-hit != 'true' }}
          run: |
              echo "::group::Nix store export"
              nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache
              echo "::endgroup::"
